// SPDX-License-Identifier: MIT
//! Render Geyser's config.yml from [`crate::Options`].

use std::fs::OpenOptions;
use std::io::Write;
use std::os::unix::fs::OpenOptionsExt;
use std::path::Path;

use crate::error::Result;
use crate::options::{AuthType, Options};

pub(crate) fn render_config(workdir: &Path, opts: &Options) -> Result<()> {
    let (bedrock_addr, bedrock_port) = split_host_port(&opts.listen, "0.0.0.0", "19132");
    let (upstream_addr, upstream_port) = split_host_port(&opts.upstream, "127.0.0.1", "25565");
    let motd1 = if opts.motd.line1.is_empty() {
        "geyserlite".into()
    } else {
        opts.motd.line1.clone()
    };
    let motd2 = if opts.motd.line2.is_empty() {
        "cross-play".into()
    } else {
        opts.motd.line2.clone()
    };
    let floodgate_line = if opts.auth_type == AuthType::Floodgate {
        "floodgate-key-file: key.bin\n"
    } else {
        ""
    };

    let body = format!(
        "# Generated by go.minekube.com/geyserlite/rust.\n\
bedrock:\n  \
  address: {bedrock_addr}\n  \
  port: {bedrock_port}\n  \
  motd1: '{motd1}'\n  \
  motd2: '{motd2}'\n  \
  server-name: {motd1}\n  \
  compression-level: 6\n\
\n\
java:\n  \
  address: {upstream_addr}\n  \
  port: {upstream_port}\n  \
  auth-type: {auth}\n  \
  use-proxy-protocol: {floodgate}\n  \
  forward-hostname: true\n\
\n\
{floodgate_line}\
\n\
passthrough-motd: false\n\
passthrough-player-counts: false\n\
legacy-ping-passthrough: false\n\
\n\
forward-player-ping: true\n\
max-players: 100\n\
debug-mode: false\n\
\n\
show-cooldown: title\n\
show-coordinates: true\n\
disable-bedrock-scaffolding: false\n\
\n\
xbox-achievements-enabled: false\n\
log-player-ip-addresses: true\n\
notify-on-new-bedrock-update: false\n\
\n\
scoreboard-packet-threshold: 20\n\
enable-proxy-connections: false\n\
mtu: 1400\n\
use-direct-connection: false\n\
disable-compression: false\n\
\n\
config-version: 4\n",
        auth = opts.auth_type.as_str(),
        floodgate = opts.auth_type == AuthType::Floodgate,
    );

    let path = workdir.join("config.yml");
    let mut f = OpenOptions::new()
        .create(true)
        .truncate(true)
        .write(true)
        .mode(0o600)
        .open(&path)?;
    f.write_all(body.as_bytes())?;
    Ok(())
}

pub(crate) fn write_floodgate_key(workdir: &Path, opts: &Options) -> Result<()> {
    if opts.auth_type != AuthType::Floodgate {
        return Ok(());
    }
    if opts.floodgate_key.len() != 16 {
        return Err(crate::Error::InvalidFloodgateKey);
    }
    let path = workdir.join("key.bin");
    let mut f = OpenOptions::new()
        .create(true)
        .truncate(true)
        .write(true)
        .mode(0o600)
        .open(&path)?;
    f.write_all(&opts.floodgate_key)?;
    Ok(())
}

pub(crate) fn write_permissions_yml(workdir: &Path) -> Result<()> {
    let path = workdir.join("permissions.yml");
    std::fs::write(path, "default-permissions: []\n")?;
    Ok(())
}

/// Split "host:port" with defaults for missing pieces. Handles IPv6 in brackets.
pub(crate) fn split_host_port<'a>(
    s: &'a str,
    default_host: &'a str,
    default_port: &'a str,
) -> (String, String) {
    if s.is_empty() {
        return (default_host.into(), default_port.into());
    }
    if let Some(rest) = s.strip_prefix('[') {
        if let Some(end) = rest.find(']') {
            let host = &rest[..end];
            let after = &rest[end + 1..];
            let port = after.strip_prefix(':').unwrap_or(default_port);
            return (host.into(), port.into());
        }
    }
    if let Some(idx) = s.rfind(':') {
        let host = if idx == 0 {
            default_host.to_string()
        } else {
            s[..idx].to_string()
        };
        return (host, s[idx + 1..].to_string());
    }
    (s.into(), default_port.into())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn split_simple() {
        assert_eq!(
            split_host_port("127.0.0.1:25567", "0.0.0.0", "19132"),
            ("127.0.0.1".into(), "25567".into())
        );
    }
    #[test]
    fn split_default_host() {
        assert_eq!(
            split_host_port(":19132", "0.0.0.0", "19132"),
            ("0.0.0.0".into(), "19132".into())
        );
    }
    #[test]
    fn split_ipv6() {
        assert_eq!(
            split_host_port("[::1]:25567", "0.0.0.0", "19132"),
            ("::1".into(), "25567".into())
        );
    }
    #[test]
    fn split_fly() {
        assert_eq!(
            split_host_port("fly-global-services:19132", "0.0.0.0", "19132"),
            ("fly-global-services".into(), "19132".into())
        );
    }
}
