// SPDX-License-Identifier: MIT
package geyserlite

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// renderConfig writes a Geyser config.yml into workdir based on opts.
//
// Geyser standalone reads config.yml from cwd; the runner sets cwd to
// workdir before launch.
func renderConfig(workdir string, opts Options) error {
	listenAddr, listenPort := splitHostPort(opts.Listen, "0.0.0.0", "19132")
	upstreamAddr, upstreamPort := splitHostPort(opts.Upstream, "127.0.0.1", "25565")

	data := configData{
		BedrockAddr:  listenAddr,
		BedrockPort:  listenPort,
		MOTD1:        defaultStr(opts.MOTD.Line1, "geyserlite"),
		MOTD2:        defaultStr(opts.MOTD.Line2, "cross-play"),
		ServerName:   defaultStr(opts.MOTD.Line1, "geyserlite"),
		UpstreamAddr: upstreamAddr,
		UpstreamPort: upstreamPort,
		AuthType:     opts.AuthType.String(),
		Floodgate:    opts.AuthType == Floodgate,
	}
	var buf strings.Builder
	if err := configTmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("geyserlite: render config: %w", err)
	}
	path := filepath.Join(workdir, "config.yml")
	if err := os.WriteFile(path, []byte(buf.String()), 0o600); err != nil {
		return fmt.Errorf("geyserlite: write config.yml: %w", err)
	}
	return nil
}

type configData struct {
	BedrockAddr, BedrockPort   string
	UpstreamAddr, UpstreamPort string
	MOTD1, MOTD2               string
	ServerName                 string
	AuthType                   string
	Floodgate                  bool
}

var configTmpl = template.Must(template.New("config").Parse(`# Generated by go.minekube.com/geyserlite/go.
bedrock:
  address: {{.BedrockAddr}}
  port: {{.BedrockPort}}
  motd1: '{{.MOTD1}}'
  motd2: '{{.MOTD2}}'
  server-name: {{.ServerName}}
  compression-level: 6

java:
  address: {{.UpstreamAddr}}
  port: {{.UpstreamPort}}
  auth-type: {{.AuthType}}
  use-proxy-protocol: {{if .Floodgate}}true{{else}}false{{end}}
  forward-hostname: true

{{if .Floodgate}}floodgate-key-file: key.bin{{end}}

passthrough-motd: false
passthrough-player-counts: false
legacy-ping-passthrough: false

forward-player-ping: true
max-players: 100
debug-mode: false

show-cooldown: title
show-coordinates: true
disable-bedrock-scaffolding: false

xbox-achievements-enabled: false
log-player-ip-addresses: true
notify-on-new-bedrock-update: false

scoreboard-packet-threshold: 20
enable-proxy-connections: false
mtu: 1400
use-direct-connection: false
disable-compression: false

config-version: 4
`))

// splitHostPort splits "host:port"; missing pieces fall back to defaults.
func splitHostPort(s, defaultHost, defaultPort string) (string, string) {
	if s == "" {
		return defaultHost, defaultPort
	}
	// IPv6 in brackets: "[::1]:25567"
	if strings.HasPrefix(s, "[") {
		end := strings.Index(s, "]")
		if end < 0 {
			return defaultHost, defaultPort
		}
		host := s[1:end]
		rest := s[end+1:]
		if !strings.HasPrefix(rest, ":") {
			return host, defaultPort
		}
		return host, rest[1:]
	}
	idx := strings.LastIndex(s, ":")
	if idx < 0 {
		return s, defaultPort
	}
	host := s[:idx]
	if host == "" {
		host = defaultHost
	}
	return host, s[idx+1:]
}

func defaultStr(s, fallback string) string {
	if s == "" {
		return fallback
	}
	return s
}
