// SPDX-License-Identifier: MIT
package geyserlite

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

// renderConfig writes a Geyser config.yml into workdir based on opts.
//
// The flow is: parse a baseline YAML → fold the typed [Options] knobs
// (Listen, Upstream, AuthType, MOTD) onto it → deep-merge
// [Options.ConfigOverrides] last → marshal back to YAML. That makes
// the typed knobs the easy path while leaving every Geyser config
// option reachable through ConfigOverrides for the long-tail of
// settings the typed surface doesn't model.
//
// Geyser standalone reads config.yml from the path we pass; the runner
// provides an absolute config path. Geyser's getConfigFolder() is patched
// via apply-overlay.sh to return the config file's parent directory,
// so relative-path lookups (permissions.yml, key.bin) resolve without
// relying on process CWD.
func renderConfig(workdir string, opts Options) error {
	cfg, err := buildConfigMap(opts)
	if err != nil {
		return err
	}
	out, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("geyserlite: marshal config: %w", err)
	}
	path := filepath.Join(workdir, "config.yml")
	if err := os.WriteFile(path, out, 0o600); err != nil {
		return fmt.Errorf("geyserlite: write config.yml: %w", err)
	}
	return nil
}

// buildConfigMap is renderConfig's pure-data half. Exposed so tests
// can assert the merge result without writing files.
func buildConfigMap(opts Options) (map[string]any, error) {
	var cfg map[string]any
	if err := yaml.Unmarshal([]byte(baselineConfigYAML), &cfg); err != nil {
		return nil, fmt.Errorf("geyserlite: parse baseline config: %w", err)
	}

	listenAddr, listenPort := splitHostPort(opts.Listen, "0.0.0.0", 19132)
	upstreamAddr, upstreamPort := splitHostPort(opts.Upstream, "127.0.0.1", 25565)

	mergeMap(cfg, map[string]any{
		"bedrock": map[string]any{
			"address":     listenAddr,
			"port":        listenPort,
			"motd1":       defaultStr(opts.MOTD.Line1, "geyserlite"),
			"motd2":       defaultStr(opts.MOTD.Line2, "cross-play"),
			"server-name": defaultStr(opts.MOTD.Line1, "geyserlite"),
		},
		"java": map[string]any{
			"address":            upstreamAddr,
			"port":               upstreamPort,
			"auth-type":          opts.AuthType.String(),
			"use-proxy-protocol": opts.AuthType == Floodgate,
			"forward-hostname":   true,
		},
	})
	if opts.AuthType == Floodgate {
		cfg["floodgate-key-file"] = "key.bin"
	}

	if len(opts.ConfigOverrides) > 0 {
		mergeMap(cfg, opts.ConfigOverrides)
	}
	return cfg, nil
}

// mergeMap recursively merges src into dst. When both sides have a
// nested map at the same key, recurse; otherwise src wins. Leaves
// untouched keys that src doesn't mention. Mirrors Gate's
// pkg/edition/bedrock/geyser/managed mergeConfigMaps.
func mergeMap(dst, src map[string]any) {
	for k, v := range src {
		if existing, ok := dst[k]; ok {
			if dstMap, ok := existing.(map[string]any); ok {
				if srcMap, ok := v.(map[string]any); ok {
					mergeMap(dstMap, srcMap)
					continue
				}
			}
		}
		dst[k] = v
	}
}

// baselineConfigYAML is the starting point every renderConfig call
// merges on top of. Values here are Geyser-recommended defaults that
// also work for the embedded use case (passthrough off because Gate
// is typically the upstream, debug-mode off, sane perf knobs).
//
// To override anything in here per-instance, use Options.ConfigOverrides.
const baselineConfigYAML = `# Generated by go.minekube.com/geyserlite.
bedrock:
  address: 0.0.0.0
  port: 19132
  motd1: geyserlite
  motd2: cross-play
  server-name: geyserlite
  compression-level: 6

java:
  address: 127.0.0.1
  port: 25565
  auth-type: floodgate
  use-proxy-protocol: false
  forward-hostname: true

passthrough-motd: false
passthrough-player-counts: false
legacy-ping-passthrough: false

forward-player-ping: true
max-players: 100
debug-mode: false

show-cooldown: title
show-coordinates: true
disable-bedrock-scaffolding: false

xbox-achievements-enabled: false
log-player-ip-addresses: true
notify-on-new-bedrock-update: false

scoreboard-packet-threshold: 20
enable-proxy-connections: false
mtu: 1400
use-direct-connection: false
disable-compression: false

config-version: 4
`

// splitHostPort splits "host:port"; missing pieces fall back to
// defaults. Port comes out as int since YAML int is what Geyser
// expects (a string would still parse but stir up type confusion in
// ConfigOverrides merges).
func splitHostPort(s, defaultHost string, defaultPort int) (string, int) {
	if s == "" {
		return defaultHost, defaultPort
	}
	host, portStr := splitHostPortStr(s)
	if host == "" {
		host = defaultHost
	}
	if portStr == "" {
		return host, defaultPort
	}
	port, err := strconv.Atoi(portStr)
	if err != nil {
		return host, defaultPort
	}
	return host, port
}

func splitHostPortStr(s string) (host, port string) {
	// IPv6 in brackets: "[::1]:25567"
	if strings.HasPrefix(s, "[") {
		end := strings.Index(s, "]")
		if end < 0 {
			return "", ""
		}
		rest := s[end+1:]
		if !strings.HasPrefix(rest, ":") {
			return s[1:end], ""
		}
		return s[1:end], rest[1:]
	}
	idx := strings.LastIndex(s, ":")
	if idx < 0 {
		return s, ""
	}
	return s[:idx], s[idx+1:]
}

func defaultStr(s, fallback string) string {
	if s == "" {
		return fallback
	}
	return s
}
